export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';

export const LOAD_POSTS_SUCCESS = 'LOAD_POST_SUCCESS';
export const POST_SUCCESS = 'POST_SUCCESS';

export const SIGN_IN_USER = 'SIGN_IN_USER';
export const SIGN_OUT_USER = 'SIGN_OUT_USER';
export const SIGNED_OUT = 'SIGNED_OUT';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_USER = 'AUTH_USER';
export const CLEAN_ERROR = 'CLEAN_ERROR';

export const BEGIN_APP_PROCESSING = 'BEGIN_APP_PROCESSING'
export const END_APP_PROCESSING = 'END_APP_PROCESSING'

export const CREATE_MOVIE_ERROR = 'CREATE_MOVIE_ERROR';
export const CREATE_MOVIE_SUCCESS = 'CREATE_MOVIE_SUCCESS';
export const LOAD_MOVIES_SUCCESS = 'LOAD_MOVIES_SUCCESS';
export const FILTER_MOVIES = 'FILTER_MOVIES';
export const UNLOAD_MOVIES_SUCCESS = 'UNLOAD_MOVIES_SUCCESS';

export const SEND_EMAIL_ERROR = 'SEND_EMAIL_ERROR';
export const SEND_EMAIL_SUCCESS = 'SEND_EMAIL_SUCCESS';
